sudo: required

language: node_js

node_js:
  - 8
  - 7
  - 6

dist: trusty

services:
  - docker

env:
  matrix:
    - DOCKER_TAG=1.13-dind
    - DOCKER_TAG=1.12-dind
  global:
    - DEBUG='navy:*' NAVY_DEBUG='navy:*' DOCKER_COMPOSE_VERSION=1.10.1

cache:
  directories:
    - $(npm config get cache)

matrix:
  fast_finish: true

  include:
    - node_js: 6
      env: DOCKER_TAG=1.11-dind
    - node_js: 6
      env: DOCKER_TAG=1.10-dind

before_install:
  # print versions
  - docker --version

before_script:
  # bootstrap packages
  - npm run bootstrap
