sudo: required

language: node_js

node_js:
  - 8
  - 10

dist: trusty

services:
  - docker

env:
  matrix:
    - DOCKER_TAG=18.06-dind
    - DOCKER_TAG=18.09-dind
  global:
    - DEBUG='navy:*' NAVY_DEBUG='navy:*' DOCKER_COMPOSE_VERSION=1.23.1

cache:
  directories:
    - $(npm config get cache)

matrix:
  fast_finish: true

  include:
    - node_js: 10
      env: DOCKER_TAG=18.06-dind DOCKER_COMPOSE_VERSION=1.14.0
    - node-js: 10
      env: DOCKER_TAG=18.06-dind DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  # print versions
  - docker --version

before_script:
  # bootstrap packages
  - npm run bootstrap
